
services:
  # Indexer
  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    env_file:
      - common.env
    volumes:
      - "./config/prowlarr:/config"
    ports:
      - "9696:9696"

  # Movies
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    env_file:
      - common.env
    volumes:
      - "/bulk/htpc_media/Downloads/torrents:/downloads/torrents"
      - "/bulk/htpc_media/Downloads/usenet:/downloads/usenet"
      - "/bulk/htpc_media/Movies:/movies"
      - "./config/radarr:/config"
    ports:
      - "7878:7878"

  # TV Shows
  sonarr:
    image: linuxserver/sonarr:develop
    container_name: sonarr
    restart: unless-stopped
    env_file:
      - common.env
    volumes:
      - "/bulk/htpc_media/Downloads/torrents:/downloads/torrents"
      - "/bulk/htpc_media/Downloads/usenet:/downloads/usenet"
      - "/bulk/htpc_media/TV Shows:/tv"
      - "/bulk/htpc_media/Anime:/anime"
      - "./config/sonarr:/config"
    ports:
      - "8989:8989"

  # TV Shows
  sonarr_anime:
    image: linuxserver/sonarr:develop
    container_name: sonarr_anime
    restart: unless-stopped
    env_file:
      - common.env
    volumes:
      - "/bulk/htpc_media:/data"
      - "./config/sonarr_anime:/config"
    ports:
      - "8988:8989"
 
  
  # Sync TraSH Guides
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    restart: unless-stopped
    user: 1029:100
    volumes: 
      - "./config/recyclarr:/config"
    environment: 
      TZ: America/New_York

  # Subtitles
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    restart: unless-stopped
    volumes:
      - "./config/bazarr:/config"
      - "/bulk/htpc_media/TV Shows:/tv"
      - "/bulk/htpc_media/Movies:/movies"
      - "/bulk/htpc_media/Anime:/anime"
    env_file:
      - common.env
    ports:
      - "6767:6767"

  # Usenet (nzb) Download Client
  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    env_file:
      - common.env
    volumes:
      - "./downloads:/downloads/incomplete"
      - "/bulk/htpc_media/Downloads/usenet:/downloads/complete"
      - "./config/sabnzbd:/config"
    ports:
      - "18080:8080"
      - "19090:9090"

  # Container Orchestration
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    environment:
      VIRTUAL_PORT: 9000
      VIRTUAL_HOST: htpc.home.arpa
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"

  # Plex Metrics
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped   
    env_file:
      - common.env
    volumes:
      - "./config/tautulli:/config"
      - "./logs/plex/:/mnt/plexlogs/"
    ports:
      - "8181:8181"

  pia:
    image: j4ym0/pia-qbittorrent
    container_name: pia
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - "/bulk/htpc_media:/data"
      - "./config/pia:/config"
    ports:
      - 8888:8888
    environment:
      REGION: ${OPENVPN_CONFIG}
      USER: ${OPENVPN_USERNAME}
      PASSWORD: ${OPENVPN_PASSWORD}
    profiles:
      - bt

  flood:
    hostname: flood
    image: jesec/flood
    user: 1029:100
    restart: unless-stopped
    command: --port 3001 --allowedpath /data
    environment:
      HOME: /config
    volumes:
      - "./config/flood/config:/config"
      - "/bulk/htpc_media:/data"
    ports:
      - 3001:3001


  # Request Manager
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    environment:
      LOG_LEVEL: debug
      TZ: America/New_York
    ports:
      - 5055:5055
    volumes:
      - "./config/overseerr:/app/config"

  # Transcode engine
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    network_mode: bridge
    restart: unless-stopped
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # Internal node port
      - 8268:8268 # Example extra node port
    env_file:
      - common.env
      - transcode.env
    environment:
      webUIPort: 8265
      internalNode: true
      nodeName: MyInternalNode
    volumes:
      - "./config/tdarr/server:/app/server"
      - "./config/tdarr/config:/app/configs"
      - "./config/tadarr/logs:/app/logs"
      - "/bulk/htpc_media:/media"
      - "/fast/vol2/transcode_cache:/temp"
    profiles:
      - transcode

  tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    network_mode: service:tdarr
    restart: unless-stopped
    env_file:
      - common.env
      - transcode.env
    environment:
      nodeName: MainNode
    volumes:
      - "./config/tdarr/configs:/app/configs"
      - "./config/tdarr/logs:/app/logs"
      - "/bulk/htpc_media:/media"
      - "/fast/vol2/transcode_cache:/temp"
    profiles:
      - transcode

volumes:
  portainer_data:
    external: true

  recyclarr_data:
    external: true


