services:
lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    env_file:
      - common.env
    volumes:
      - "./config/lidarr:/config"
      - "music:/music"
    ports:
      - "8686:8686"
    restart: unless-stopped
 

volumes:
  # Media Network File Share
  nasmusic:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.home.arpa,rw,soft
      device: ":/volume1/media/Music"


