---

version: '3.9'
services:
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    volumes:
      - "./config/lidarr:/config"
      - "music:/music"
    environment:
      - PUID=${PUID:-1029}
      - PGID=${PGID:-100}
      - TZ=${TZ:-America/New_York}
    ports:
      - "8686:8686"
       
volumes:
  music:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas.lan.piggah.xyz,rw,soft
      device: ":/volume1/media/Music"
